// SPDX-License-Identifier: CC0-1.0
// Public-domain example code (CC0) - see LICENSE. The CAS BACnet Stack itself is
// a separate, commercially licensed product and is not covered by CC0.
// =============================================================================
// BACnet Profile Example - B-ACDC (Access Control Door Controller) - C++
//
// This example implements the BACnet "B-ACDC" (Access Control Door Controller)
// device profile with the CAS BACnet Stack. It is the B-SS (Smart Sensor)
// example plus the one thing that makes a door controller: an Access Door object
// that a client can LOCK and UNLOCK with WriteProperty.
//
// A B-ACDC (ANSI/ASHRAE 135, Annex L.7 - Miscellaneous) is a small, focused
// device. Its mandatory capabilities are:
//
//     DS-RP-B    - respond to ReadProperty requests (like B-SS)
//     DS-WP-B    - allow other devices to WriteProperty its objects
//     DS-ACAD-B  - present an Access Door object whose Present_Value is
//                  readable and writable (this is the profile's defining BIBB)
//     DM-DDB-B   - answer Who-Is with I-Am        (handled by the stack)
//     DM-DOB-B   - answer Who-Has with I-Have     (handled by the stack)
//
// A B-ACDC requires NO alarms/events, NO scheduling, NO trending, and NO COV -
// so this example deliberately does not enable any of them. That is the whole
// point of a profile example: implement exactly what the profile asks for,
// nothing more. (A door controller that ALSO reports access events is a
// B-ACC / B-AACC - a different, larger profile with its own example.)
//
// The device keeps the three read-only sensor objects from B-SS and adds the one
// object this profile exists for. Each object has a colour name (the convention
// shared across this example series):
//
//     Device 389011          "Rainbow"    (instance configurable with --deviceID)
//     Analog Input  1        "Bronze"     (REAL, degrees Celsius; read-only)
//     Binary Input  1        "Emerald"    (active / inactive; read-only)
//     Multi-State Input 1    "Hot Pink"   (state 1..3; read-only)
//     Access Door 1          "Cobalt"     (lock / unlock; WRITABLE, commandable)
//     Network Port 1         "Vermilion"  (the BACnet/IP port - required)
//
// THE ACCESS DOOR IS COMMANDABLE. This is the key thing to understand, and it is
// the same mechanism the B-SA (Smart Actuator) example uses for its outputs: the
// door's Present_Value is NOT stored directly. It is resolved by the stack from a
// 16-slot BACnet Priority_Array plus a Relinquish_Default. A
// WriteProperty(Present_Value, value, priority) sets a slot; writing NULL
// relinquishes it; the stack reports the highest-priority non-null slot (or
// Relinquish_Default) as the effective Present_Value. The application stores the
// array (see the Commandable struct below) and serves it; the stack computes
// Present_Value from it. Because a door is life-safety-adjacent hardware, this
// priority mechanism is exactly what you want: a fire-alarm system can command
// the door at a high priority and a badge reader at a low one, and BACnet
// resolves who wins.
//
// To be a conformant BACnet device (Protocol_Revision 24) each object must
// expose its full set of REQUIRED properties. Most are generated by the stack
// (Object_Identifier, Object_Type, Status_Flags, Event_State, Reliability,
// Object_List, Protocol_*). The handful the application must supply are served by
// the Get*Property callbacks below. Note that an Access Door has three REQUIRED
// timing properties that no other object in this series has - Door_Pulse_Time,
// Door_Extended_Pulse_Time, and Door_Open_Too_Long_Time - and this example serves
// all three.
//
// Interactive keys (handled by the shared helper): h = help, q = quit,
// up/down = nudge Analog Input 1 by +/-1.1. Command line: --port <n>,
// --deviceID <n>.
//
// All the UDP/stack plumbing lives in common/CASExampleHelper so this file can
// stay focused on the BACnet logic.
// =============================================================================

#include "CASExampleHelper.h"
#include "CASBACnetStackExampleConstants.h"
#include "CASBACnetStackDLL.h" // the CAS BACnet Stack C API (BACnetStack_*)

#include <stdio.h>
#include <string.h>

#if defined(_WIN32)
#include <windows.h> // Sleep()
#else
#include <unistd.h>  // usleep()
#endif

using namespace CASBACnetStackExampleConstants;

// -----------------------------------------------------------------------------
// 0. Access-Control constants used only by this example
//
// The shared common/CASBACnetStackExampleConstants.h carries the enumeration
// values every example needs. The Access Door values below are specific to this
// profile, so they live here - the same style, with the stack header that owns
// the full enumeration cited above each block. Copy these into your own project
// alongside the ones you take from common/.
// -----------------------------------------------------------------------------

// -- Access Door object type (Object_Type enumeration) ----------------------
//    Full list: submodules/cas-bacnet-stack/source/BACnetObjectType.h
static const uint16_t OBJECT_TYPE_ACCESS_DOOR = 30;

// -- Access Door property identifiers (Property_Identifier enumeration) ------
//    Full list: submodules/cas-bacnet-stack/source/BACnetPropertyIdentifier.h
static const uint32_t PROPERTY_IDENTIFIER_RELIABILITY = 103;
static const uint32_t PROPERTY_IDENTIFIER_DOOR_EXTENDED_PULSE_TIME = 227;
static const uint32_t PROPERTY_IDENTIFIER_DOOR_OPEN_TOO_LONG_TIME = 229;
static const uint32_t PROPERTY_IDENTIFIER_DOOR_PULSE_TIME = 230;
static const uint32_t PROPERTY_IDENTIFIER_DOOR_STATUS = 231;
static const uint32_t PROPERTY_IDENTIFIER_LOCK_STATUS = 233;
static const uint32_t PROPERTY_IDENTIFIER_SECURED_STATUS = 235;

// -- BACnetDoorValue - what an Access Door's Present_Value means -------------
//    Full list: submodules/cas-bacnet-stack/source/BACnetDoorValue.h
//    This is what a client WRITES to lock or unlock the door.
static const uint32_t DOOR_VALUE_LOCK = 0;
static const uint32_t DOOR_VALUE_UNLOCK = 1;
static const uint32_t DOOR_VALUE_PULSE_UNLOCK = 2;          // momentary unlock
static const uint32_t DOOR_VALUE_EXTENDED_PULSE_UNLOCK = 3; // longer momentary unlock

// -- BACnetDoorStatus (optional Door_Status) - is the door physically shut? --
//    Full list: submodules/cas-bacnet-stack/source/BACnetDoorStatus.h
static const uint32_t DOOR_STATUS_CLOSED = 0;

// -- BACnetLockStatus (optional Lock_Status) - is the latch thrown? ----------
static const uint32_t LOCK_STATUS_LOCKED = 0;
static const uint32_t LOCK_STATUS_UNLOCKED = 1;

// -- BACnetDoorSecuredStatus (optional Secured_Status) ----------------------
static const uint32_t SECURED_STATUS_SECURED = 0;
static const uint32_t SECURED_STATUS_UNSECURED = 1;

// -- BACnetReliability - required on an Access Door -------------------------
//    Full list: submodules/cas-bacnet-stack/source/BACnetReliability.h
static const uint32_t RELIABILITY_NO_FAULT_DETECTED = 0;

// -----------------------------------------------------------------------------
// 1. Example + device configuration
// -----------------------------------------------------------------------------
static const char* APP_NAME = "BACnet B-ACDC (Access Control Door Controller) Example - C++";
static const char* APP_VERSION = "1.0.0";

// The device instance. BACnet requires this to be configurable, so it defaults
// to 389011 (each profile example in the series has its own default, so several
// examples can run on one subnet) and can be overridden with --deviceID.
static uint32_t g_deviceInstance = 389011;

// ---- Device identity: CHANGE ALL OF THIS BEFORE YOU SHIP --------------------
// Everything in this block is read by clients and shown to the operator in every
// discovery tool on the network. Left as-is, your product will appear on a real
// site announcing itself as a Chipkin demo. None of it is cosmetic:
// Object_Name must be unique across the BACnet internetwork, and Model_Name /
// Vendor_Identifier are what a building operator uses to identify your device.
// -----------------------------------------------------------------------------

// Your BACnet Vendor Identifier. 389 = Chipkin Automation Systems; change this
// to YOUR company's vendor ID before shipping a product. Vendor IDs are assigned
// by ASHRAE - request one (free) at https://bacnet.org/assigned-vendor-ids/.
// Update VENDOR_NAME below to match.
static const uint32_t VENDOR_IDENTIFIER = 389;
static const char* DEVICE_NAME = "Rainbow";
static const char* DEVICE_DESCRIPTION =
    "Chipkin CAS BACnet Stack example - B-ACDC (Access Control Door Controller) profile. "
    "Demonstrates DS-ACAD-B: an Access Door object locked and unlocked with WriteProperty.";

// Device identity strings (read by clients, and used to populate I-Am).
static const char* VENDOR_NAME = "Chipkin Automation Systems";
static const char* MODEL_NAME = "CAS BACnet Stack Example - B-ACDC";
static const char* FIRMWARE_REVISION = "1.0.0";
static const char* APPLICATION_SOFTWARE_VERSION = "1.0.0";

// The sensor objects (all instance 1) and their colour names.
static const uint32_t ANALOG_INPUT_INSTANCE = 1;       // "Bronze"
static const uint32_t BINARY_INPUT_INSTANCE = 1;       // "Emerald"
static const uint32_t MULTI_STATE_INPUT_INSTANCE = 1;  // "Hot Pink"
static const uint32_t MULTI_STATE_INPUT_NUMBER_OF_STATES = 3;

// The Network Port object - every BACnet device must have one. It represents
// the BACnet/IP port this device communicates on.
static const uint32_t NETWORK_PORT_INSTANCE = 1;       // "Vermilion"
static const uint32_t MAX_APDU_LENGTH = 1476;          // BACnet/IP APDU length

// BACnet/IP addressing the Network Port reports. The IP address and subnet mask
// are filled in at start-up from the host's primary interface; the gateway is
// left unset (0.0.0.0) for this example. The stack also uses IP_Address +
// BACnet_IP_UDP_Port to build the port's MAC_Address automatically.
static uint8_t g_ipAddress[4] = { 0, 0, 0, 0 };
static uint8_t g_ipSubnetMask[4] = { 0, 0, 0, 0 };
static uint8_t g_ipDefaultGateway[4] = { 0, 0, 0, 0 };
static uint16_t g_bacnetIpUdpPort = 47808;

// Analog Input 1's live present value (degrees Celsius). Starts at 21.5 and is
// nudged by the up/down arrow keys. A real sensor would update this from
// hardware instead.
static float g_analogInput1Value = 21.5f;

// --- The Access Door (the B-ACDC addition) -----------------------------------
static const uint32_t ACCESS_DOOR_INSTANCE = 1;        // "Cobalt"
static const uint32_t BACNET_PRIORITY_ARRAY_SIZE = 16;

// The Access Door's three REQUIRED timing properties, in tenths of a second (the
// units BACnet defines for them - clause 12.3). A real door controller would
// drive its strike/latch hardware with exactly these numbers:
//   Door_Pulse_Time          - how long a pulseUnlock holds the door unlocked.
//   Door_Extended_Pulse_Time - the same, for extendedPulseUnlock (e.g. an
//                              accessibility door that must stay open longer).
//   Door_Open_Too_Long_Time  - how long the door may stand open before the
//                              controller considers it a problem.
static const uint32_t DOOR_PULSE_TIME = 30;            // 3.0 seconds
static const uint32_t DOOR_EXTENDED_PULSE_TIME = 100;  // 10.0 seconds
static const uint32_t DOOR_OPEN_TOO_LONG_TIME = 300;   // 30.0 seconds

// A BACnet commandable value: a 16-slot Priority_Array plus a Relinquish_Default.
// Each slot is either null (relinquished) or holds a commanded value. A real
// device would map the resolved Present_Value onto its physical output; here we
// just store the commands. This struct is identical to the one in the B-SA
// example - a commandable object works the same way whatever its object type.
struct Commandable {
    bool isSet[16];           // is slot i (1..16) commanded?
    double value[16];         // the commanded value at slot i
    double relinquishDefault; // used when every slot is null
};

// The door defaults to LOCKED when nothing commands it. That is the safe resting
// state for an access-control door: if every priority slot is relinquished, the
// door locks.
// The { { false }, { 0 }, default } initializer zero-fills all 16 slots of isSet
// and value (C++ aggregate rules: the remaining elements are value-initialized),
// so every priority slot starts null and Present_Value reports relinquishDefault.
static Commandable g_accessDoor = { { false }, { 0 }, (double)DOOR_VALUE_LOCK };

// A WriteProperty to a commandable Present_Value carries a priority 1..16. When a
// client omits it, BACnet uses 16 (the lowest priority) - so normalise anything
// out of range to 16, matching the stack's own behaviour.
static uint8_t EffectivePriority(uint8_t priority) {
    return (priority >= 1 && priority <= BACNET_PRIORITY_ARRAY_SIZE) ? priority : 16;
}

// Store a commanded value at a priority slot (a WriteProperty of a value).
static void CommandWrite(Commandable* c, uint8_t priority, double value) {
    const uint8_t p = EffectivePriority(priority);
    c->isSet[p - 1] = true;
    c->value[p - 1] = value;
}

// Relinquish (clear) a priority slot - i.e. a WriteProperty of NULL.
static void CommandRelinquish(Commandable* c, uint8_t priority) {
    const uint8_t p = EffectivePriority(priority);
    c->isSet[p - 1] = false;
}

// Resolve which Commandable an (objectType, objectInstance) maps to, or NULL.
// This example has exactly one commandable object - the door.
static Commandable* GetCommandable(uint16_t objectType, uint32_t objectInstance) {
    if (objectType == OBJECT_TYPE_ACCESS_DOOR && objectInstance == ACCESS_DOOR_INSTANCE) {
        return &g_accessDoor;
    }
    return NULL;
}

// Is this read a single Priority_Array element (Priority_Array[1..16])? If so,
// report whether that slot is commanded (*slotIsSet) and its value (*slotValue).
// The typed Get callbacks use this to serve a commandable object's Priority_Array
// and to let the stack compute Present_Value from the highest non-null slot.
static bool ReadPrioritySlot(const Commandable* c, uint32_t propertyIdentifier,
                             bool useArrayIndex, uint32_t propertyArrayIndex,
                             bool* slotIsSet, double* slotValue) {
    if (propertyIdentifier != PROPERTY_IDENTIFIER_PRIORITY_ARRAY || !useArrayIndex ||
        propertyArrayIndex < 1 || propertyArrayIndex > BACNET_PRIORITY_ARRAY_SIZE) {
        return false;
    }
    *slotIsSet = c->isSet[propertyArrayIndex - 1];
    *slotValue = c->value[propertyArrayIndex - 1];
    return true;
}

// Resolve the door's effective Present_Value the same way the stack does: the
// highest-priority commanded slot wins, otherwise Relinquish_Default. We only
// need this to PRINT the door's state - the stack serves Present_Value itself.
static uint32_t ResolveDoorValue(const Commandable* c) {
    for (uint32_t i = 0; i < BACNET_PRIORITY_ARRAY_SIZE; i++) {
        if (c->isSet[i]) {
            return (uint32_t)c->value[i];
        }
    }
    return (uint32_t)c->relinquishDefault;
}

// A human-readable name for a BACnetDoorValue, for the console log.
static const char* DoorValueName(uint32_t doorValue) {
    switch (doorValue) {
        case DOOR_VALUE_LOCK:                  return "lock";
        case DOOR_VALUE_UNLOCK:                return "unlock";
        case DOOR_VALUE_PULSE_UNLOCK:          return "pulseUnlock";
        case DOOR_VALUE_EXTENDED_PULSE_UNLOCK: return "extendedPulseUnlock";
        default:                               return "?";
    }
}

// -----------------------------------------------------------------------------
// 2. Property "get" callbacks
//
// The stack calls these when a client reads a property. For each data type the
// stack uses a separate callback. We return true (and fill *value) when we
// recognise the (object, property) pair, and false otherwise.
//
// WHAT false ACTUALLY DOES - and this is the most important paragraph in the
// file, because an earlier version of this comment got it backwards. Returning
// false does NOT reliably produce a BACnet error. The stack only errors for the
// handful of properties it refuses to invent (BACnetBusinessLogic.cpp: the
// valueShouldBeInitialized switch) - Present_Value, Number_Of_States,
// Relinquish_Default, Local_Date, Local_Time, and a Network Port's APDU_Length.
// For EVERYTHING ELSE, a false return falls through to GetDefaultPropertyValue()
// (BACnetDBDevice.cpp) and the stack SILENTLY SUBSTITUTES a default:
//     Object_Name -> the literal string "undefined"
//     Units       -> no-units (95)
//     otherwise   -> a datatype zero-value
//
// ADDING AN OBJECT? READ THIS FIRST.
// The consequence is the opposite of reassuring. These callbacks are not
// uniformly strict:
//   - GetPropertyReal / GetPropertyEnumerated / GetPropertyUnsignedInteger match
//     on object type AND INSTANCE (directly, or via GetCommandable(), which
//     looks up the exact type+instance pair). A new instance falls through every
//     one of those checks.
//   - GetPropertyBool serves Out_Of_Service on object TYPE ONLY, so a new
//     instance of an existing type gets Out_Of_Service for free.
// So a half-added object does NOT fail loudly. Its Present_Value errors (that
// one is in the list above) - but its Object_Name reads back as "undefined" and
// its Units as no-units, with no error at all. Add two objects that way and BOTH
// report Object_Name "undefined": duplicate object names within one device, which
// is a spec violation and a hard BTL failure, and which every scan tool will show
// you as a healthy object. The device looks fine and is non-conformant.
//
// So: when you add an instance, walk EVERY callback below, then read back every
// required property of the new object and DIFF IT against the existing one. Do
// not trust "it scanned OK" - that is exactly the failure mode.
// -----------------------------------------------------------------------------

// REAL (floating point) - the Analog Input's Present_Value.
bool GetPropertyReal(const uint32_t deviceInstance, const uint16_t objectType,
                     const uint32_t objectInstance, const uint32_t propertyIdentifier,
                     float* value, const bool useArrayIndex,
                     const uint32_t propertyArrayIndex) {
    (void)useArrayIndex;
    (void)propertyArrayIndex;
    if (deviceInstance == g_deviceInstance &&
        objectType == OBJECT_TYPE_ANALOG_INPUT &&
        objectInstance == ANALOG_INPUT_INSTANCE &&
        propertyIdentifier == PROPERTY_IDENTIFIER_PRESENT_VALUE) {
        // ON REAL HARDWARE: return the live sensor reading here. Read it from a
        // cached variable that your hardware updates (as g_analogInput1Value is),
        // NOT directly from a slow/blocking device (I2C, SPI, ADC conversion):
        // this callback runs on the BACnetStack_Tick() thread, so blocking it
        // delays all BACnet processing. Sample the sensor on a timer/another
        // thread and just hand back the latest value from here.
        *value = g_analogInput1Value;
        return true;
    }
    return false;
}

// ENUMERATED - the Binary Input's Present_Value, the Analog Input's Units, and
// (the B-ACDC part) the Access Door's commandable Present_Value slots plus its
// Relinquish_Default, Reliability, and optional status properties.
bool GetPropertyEnumerated(const uint32_t deviceInstance, const uint16_t objectType,
                           const uint32_t objectInstance, const uint32_t propertyIdentifier,
                           uint32_t* value, const bool useArrayIndex,
                           const uint32_t propertyArrayIndex) {
    if (deviceInstance != g_deviceInstance) {
        return false;
    }
    if (objectType == OBJECT_TYPE_BINARY_INPUT &&
        objectInstance == BINARY_INPUT_INSTANCE) {
        if (propertyIdentifier == PROPERTY_IDENTIFIER_PRESENT_VALUE) {
            *value = 1; // active
            return true;
        }
        if (propertyIdentifier == PROPERTY_IDENTIFIER_POLARITY) {
            *value = POLARITY_NORMAL; // required property of a Binary Input
            return true;
        }
    }
    if (objectType == OBJECT_TYPE_ANALOG_INPUT &&
        objectInstance == ANALOG_INPUT_INSTANCE &&
        propertyIdentifier == PROPERTY_IDENTIFIER_UNITS) {
        *value = ENGINEERING_UNITS_DEGREES_CELSIUS;
        return true;
    }
    if (objectType == OBJECT_TYPE_NETWORK_PORT &&
        objectInstance == NETWORK_PORT_INSTANCE &&
        propertyIdentifier == PROPERTY_IDENTIFIER_BACNET_IP_MODE) {
        *value = BACNET_IP_MODE_NORMAL; // not foreign-device, not BBMD
        return true;
    }

    // --- The Access Door (commandable) --------------------------------------
    // Present_Value is an enumerated BACnetDoorValue driven through the
    // Priority_Array. We serve the array slots and Relinquish_Default; the stack
    // computes Present_Value from them. (Do NOT answer Present_Value here - see
    // the note in main() and the B-SA example.)
    const Commandable* c = GetCommandable(objectType, objectInstance);
    if (c != NULL) {
        bool slotIsSet = false;
        double slotValue = 0.0;
        if (ReadPrioritySlot(c, propertyIdentifier, useArrayIndex, propertyArrayIndex,
                             &slotIsSet, &slotValue)) {
            if (!slotIsSet) {
                return false; // null slot - GetPropertyBool reports the NULL
            }
            *value = (uint32_t)slotValue;
            return true;
        }
        if (propertyIdentifier == PROPERTY_IDENTIFIER_RELINQUISH_DEFAULT) {
            *value = (uint32_t)c->relinquishDefault;
            return true;
        }
        // Reliability is a REQUIRED property of an Access Door. A real controller
        // would report a fault here when it cannot read the door hardware.
        if (propertyIdentifier == PROPERTY_IDENTIFIER_RELIABILITY) {
            *value = RELIABILITY_NO_FAULT_DETECTED;
            return true;
        }
        // The three status properties below are OPTIONAL (clause 12.3). We expose
        // them because they are what makes a door example legible: they report the
        // door's real-world state, as opposed to what it has been commanded to do.
        // We derive them from the commanded value; a real controller would read
        // them from door hardware (a reed switch, a latch monitor).
        const uint32_t doorValue = ResolveDoorValue(c);
        const bool isLocked = (doorValue == DOOR_VALUE_LOCK);
        if (propertyIdentifier == PROPERTY_IDENTIFIER_DOOR_STATUS) {
            *value = DOOR_STATUS_CLOSED; // this simulated door is always shut
            return true;
        }
        if (propertyIdentifier == PROPERTY_IDENTIFIER_LOCK_STATUS) {
            *value = isLocked ? LOCK_STATUS_LOCKED : LOCK_STATUS_UNLOCKED;
            return true;
        }
        if (propertyIdentifier == PROPERTY_IDENTIFIER_SECURED_STATUS) {
            *value = isLocked ? SECURED_STATUS_SECURED : SECURED_STATUS_UNSECURED;
            return true;
        }
    }
    return false;
}

// UNSIGNED INTEGER - the Multi-State Input's Present_Value, the Device's
// Vendor_Identifier, the Network Port's numbers, and (the B-ACDC part) the
// Access Door's three REQUIRED timing properties.
bool GetPropertyUnsignedInteger(const uint32_t deviceInstance, const uint16_t objectType,
                                const uint32_t objectInstance, const uint32_t propertyIdentifier,
                                uint32_t* value, const bool useArrayIndex,
                                const uint32_t propertyArrayIndex) {
    if (deviceInstance != g_deviceInstance) {
        return false;
    }
    if (objectType == OBJECT_TYPE_MULTI_STATE_INPUT &&
        objectInstance == MULTI_STATE_INPUT_INSTANCE) {
        if (propertyIdentifier == PROPERTY_IDENTIFIER_PRESENT_VALUE) {
            *value = 1; // state 1 (valid range is 1..Number_Of_States)
            return true;
        }
        if (propertyIdentifier == PROPERTY_IDENTIFIER_NUMBER_OF_STATES) {
            *value = MULTI_STATE_INPUT_NUMBER_OF_STATES; // required property
            return true;
        }
        // State_Text is an array. The stack asks for its LENGTH here (array
        // index 0) before reading each element via GetPropertyCharString.
        if (propertyIdentifier == PROPERTY_IDENTIFIER_STATE_TEXT &&
            useArrayIndex && propertyArrayIndex == 0) {
            *value = MULTI_STATE_INPUT_NUMBER_OF_STATES;
            return true;
        }
    }
    if (objectType == OBJECT_TYPE_DEVICE && objectInstance == g_deviceInstance &&
        propertyIdentifier == PROPERTY_IDENTIFIER_VENDOR_IDENTIFIER) {
        *value = VENDOR_IDENTIFIER;
        return true;
    }
    if (objectType == OBJECT_TYPE_NETWORK_PORT && objectInstance == NETWORK_PORT_INSTANCE) {
        if (propertyIdentifier == PROPERTY_IDENTIFIER_APDU_LENGTH) {
            *value = MAX_APDU_LENGTH;
            return true;
        }
        if (propertyIdentifier == PROPERTY_IDENTIFIER_REFERENCE_PORT) {
            *value = NETWORK_PORT_REFERENCE_PORT_NONE;
            return true;
        }
        if (propertyIdentifier == PROPERTY_IDENTIFIER_BACNET_IP_UDP_PORT) {
            *value = g_bacnetIpUdpPort;
            return true;
        }
    }

    // --- The Access Door's REQUIRED timing properties ------------------------
    // Unlike the outputs in B-SA, an Access Door has three required Unsigned
    // properties of its own. All three are in TENTHS OF A SECOND.
    if (objectType == OBJECT_TYPE_ACCESS_DOOR && objectInstance == ACCESS_DOOR_INSTANCE) {
        switch (propertyIdentifier) {
            case PROPERTY_IDENTIFIER_DOOR_PULSE_TIME:
                *value = DOOR_PULSE_TIME;
                return true;
            case PROPERTY_IDENTIFIER_DOOR_EXTENDED_PULSE_TIME:
                *value = DOOR_EXTENDED_PULSE_TIME;
                return true;
            case PROPERTY_IDENTIFIER_DOOR_OPEN_TOO_LONG_TIME:
                *value = DOOR_OPEN_TOO_LONG_TIME;
                return true;
            default:
                break;
        }
    }
    return false;
}

// BOOLEAN - Out_Of_Service (required on every object here), and the "is this
// Priority_Array slot null?" answer for the commandable Access Door.
bool GetPropertyBool(const uint32_t deviceInstance, const uint16_t objectType,
                     const uint32_t objectInstance, const uint32_t propertyIdentifier,
                     bool* value, const bool useArrayIndex,
                     const uint32_t propertyArrayIndex) {
    if (deviceInstance != g_deviceInstance) {
        return false;
    }
    // Commandable objects: the stack asks "is this Priority_Array slot null?" with
    // the boolean getter. Answer true (1) for a relinquished slot, false (0) for a
    // commanded one. This is how the stack knows which slots to skip when computing
    // Present_Value and how it encodes the NULLs in a ReadProperty of the array.
    const Commandable* c = GetCommandable(objectType, objectInstance);
    if (c != NULL && propertyIdentifier == PROPERTY_IDENTIFIER_PRIORITY_ARRAY &&
        useArrayIndex && propertyArrayIndex >= 1 &&
        propertyArrayIndex <= BACNET_PRIORITY_ARRAY_SIZE) {
        *value = !c->isSet[propertyArrayIndex - 1];
        return true;
    }
    // Out_Of_Service is a required property of every object in this example. This
    // example never takes anything out of service: false.
    if (propertyIdentifier == PROPERTY_IDENTIFIER_OUT_OF_SERVICE &&
        (objectType == OBJECT_TYPE_ANALOG_INPUT ||
         objectType == OBJECT_TYPE_BINARY_INPUT ||
         objectType == OBJECT_TYPE_MULTI_STATE_INPUT ||
         objectType == OBJECT_TYPE_ACCESS_DOOR ||
         objectType == OBJECT_TYPE_NETWORK_PORT)) {
        *value = false;
        return true;
    }
    return false;
}

// OCTET STRING - the Network Port's BACnet/IP addressing. The stack cannot know
// the host's IP, so the application must supply IP_Address and IP_Subnet_Mask
// (and IP_Default_Gateway). Each is four octets. The stack also reads IP_Address
// (with BACnet_IP_UDP_Port) to build the port's six-octet MAC_Address.
bool GetPropertyOctetString(const uint32_t deviceInstance, const uint16_t objectType,
                            const uint32_t objectInstance, const uint32_t propertyIdentifier,
                            uint8_t* value, uint32_t* valueElementCount,
                            const uint32_t maxElementCount, const bool useArrayIndex,
                            const uint32_t propertyArrayIndex) {
    (void)useArrayIndex;
    (void)propertyArrayIndex;
    if (deviceInstance != g_deviceInstance ||
        objectType != OBJECT_TYPE_NETWORK_PORT ||
        objectInstance != NETWORK_PORT_INSTANCE ||
        maxElementCount < 4) {
        return false;
    }
    const uint8_t* source = NULL;
    switch (propertyIdentifier) {
        case PROPERTY_IDENTIFIER_IP_ADDRESS:         source = g_ipAddress; break;
        case PROPERTY_IDENTIFIER_IP_SUBNET_MASK:     source = g_ipSubnetMask; break;
        case PROPERTY_IDENTIFIER_IP_DEFAULT_GATEWAY: source = g_ipDefaultGateway; break;
        default: return false;
    }
    memcpy(value, source, 4);
    *valueElementCount = 4;
    return true;
}

// Small helper: copy a C string into the stack's character-string buffer and
// set the element count + encoding. Returns true (so callers can `return`).
static bool ReturnCharacterString(const char* text, char* value,
                                  uint32_t* valueElementCount,
                                  const uint32_t maxElementCount,
                                  uint8_t* encodingType) {
    uint32_t length = (uint32_t)strlen(text);
    if (length > maxElementCount) {
        length = maxElementCount;
    }
    memcpy(value, text, length);
    *valueElementCount = length;
    *encodingType = CHARACTER_STRING_ENCODING_UTF8;
    return true;
}

// CHARACTER STRING - Object_Name for each object, and the device Description.
bool GetPropertyCharString(const uint32_t deviceInstance, const uint16_t objectType,
                           const uint32_t objectInstance, const uint32_t propertyIdentifier,
                           char* value, uint32_t* valueElementCount,
                           const uint32_t maxElementCount, uint8_t* encodingType,
                           const bool useArrayIndex, const uint32_t propertyArrayIndex) {
    if (deviceInstance != g_deviceInstance) {
        return false;
    }

    // State_Text (optional) - one label per state of the Multi-State Input. It is
    // a BACnet array, so the stack asks for one element at a time by index
    // (1..Number_Of_States). Present_Value 1 -> "On", 2 -> "Off", 3 -> "Auto".
    if (objectType == OBJECT_TYPE_MULTI_STATE_INPUT &&
        objectInstance == MULTI_STATE_INPUT_INSTANCE &&
        propertyIdentifier == PROPERTY_IDENTIFIER_STATE_TEXT && useArrayIndex) {
        static const char* const stateText[] = { "On", "Off", "Auto" };
        if (propertyArrayIndex >= 1 && propertyArrayIndex <= MULTI_STATE_INPUT_NUMBER_OF_STATES) {
            return ReturnCharacterString(stateText[propertyArrayIndex - 1], value,
                                         valueElementCount, maxElementCount, encodingType);
        }
        return false;
    }

    // Object_Name - the colour name for each object.
    if (propertyIdentifier == PROPERTY_IDENTIFIER_OBJECT_NAME) {
        if (objectType == OBJECT_TYPE_DEVICE && objectInstance == g_deviceInstance) {
            return ReturnCharacterString(DEVICE_NAME, value, valueElementCount, maxElementCount, encodingType);
        }
        if (objectType == OBJECT_TYPE_ANALOG_INPUT && objectInstance == ANALOG_INPUT_INSTANCE) {
            return ReturnCharacterString("Bronze", value, valueElementCount, maxElementCount, encodingType);
        }
        if (objectType == OBJECT_TYPE_BINARY_INPUT && objectInstance == BINARY_INPUT_INSTANCE) {
            return ReturnCharacterString("Emerald", value, valueElementCount, maxElementCount, encodingType);
        }
        if (objectType == OBJECT_TYPE_MULTI_STATE_INPUT && objectInstance == MULTI_STATE_INPUT_INSTANCE) {
            return ReturnCharacterString("Hot Pink", value, valueElementCount, maxElementCount, encodingType);
        }
        if (objectType == OBJECT_TYPE_ACCESS_DOOR && objectInstance == ACCESS_DOOR_INSTANCE) {
            return ReturnCharacterString("Cobalt", value, valueElementCount, maxElementCount, encodingType);
        }
        if (objectType == OBJECT_TYPE_NETWORK_PORT && objectInstance == NETWORK_PORT_INSTANCE) {
            return ReturnCharacterString("Vermilion", value, valueElementCount, maxElementCount, encodingType);
        }
    }

    // The remaining strings are all on the Device object - its identity, read
    // by clients and used to populate the device's I-Am / object list.
    if (objectType == OBJECT_TYPE_DEVICE && objectInstance == g_deviceInstance) {
        switch (propertyIdentifier) {
            case PROPERTY_IDENTIFIER_DESCRIPTION:
                return ReturnCharacterString(DEVICE_DESCRIPTION, value, valueElementCount, maxElementCount, encodingType);
            case PROPERTY_IDENTIFIER_VENDOR_NAME:
                return ReturnCharacterString(VENDOR_NAME, value, valueElementCount, maxElementCount, encodingType);
            case PROPERTY_IDENTIFIER_MODEL_NAME:
                return ReturnCharacterString(MODEL_NAME, value, valueElementCount, maxElementCount, encodingType);
            case PROPERTY_IDENTIFIER_FIRMWARE_REVISION:
                return ReturnCharacterString(FIRMWARE_REVISION, value, valueElementCount, maxElementCount, encodingType);
            case PROPERTY_IDENTIFIER_APPLICATION_SOFTWARE_VERSION:
                return ReturnCharacterString(APPLICATION_SOFTWARE_VERSION, value, valueElementCount, maxElementCount, encodingType);
            default:
                break;
        }
    }

    return false;
}

// -----------------------------------------------------------------------------
// 2b. Property "set" callbacks - the heart of B-ACDC (DS-WP-B / DS-ACAD-B)
//
// The stack calls these when a client sends WriteProperty to the door's
// Present_Value. The value arrives already decoded, together with the priority
// (1..16) the client wrote at. We store it in the door's Priority_Array; the
// stack recomputes Present_Value from the array on the next read. A
// WriteProperty of NULL relinquishes a slot and arrives through SetPropertyNull.
//
// Return true when we accept the write; return false (optionally setting
// *errorCode) to reject it, and the stack answers with a BACnet Error-PDU.
// -----------------------------------------------------------------------------

// ENUMERATED write - Access Door 1 (Cobalt) Present_Value: lock / unlock.
bool SetPropertyEnumerated(const uint32_t deviceInstance, const uint16_t objectType,
                           const uint32_t objectInstance, const uint32_t propertyIdentifier,
                           const uint32_t value, const bool useArrayIndex,
                           const uint32_t propertyArrayIndex, const uint8_t priority,
                           uint32_t* errorCode) {
    (void)useArrayIndex;
    (void)propertyArrayIndex;
    if (deviceInstance != g_deviceInstance) {
        return false;
    }
    Commandable* c = GetCommandable(objectType, objectInstance);
    if (c != NULL && propertyIdentifier == PROPERTY_IDENTIFIER_PRESENT_VALUE) {
        // An Access Door's Present_Value is a BACnetDoorValue: lock (0),
        // unlock (1), pulseUnlock (2), or extendedPulseUnlock (3). Reject anything
        // else with value-out-of-range - validating the written value is part of
        // being a conformant DS-WP-B / DS-ACAD-B device.
        if (value > DOOR_VALUE_EXTENDED_PULSE_UNLOCK) {
            *errorCode = ERROR_CODE_VALUE_OUT_OF_RANGE;
            return false;
        }
        CommandWrite(c, priority, (double)value);
        printf("WriteProperty: Access Door 1 (Cobalt) <- %s @ priority %u  (door is now %s)\n",
               DoorValueName(value), EffectivePriority(priority),
               DoorValueName(ResolveDoorValue(c)));
        return true;
    }
    return false;
}

// NULL write - relinquish the door's Present_Value at a priority. The stack
// routes a WriteProperty of NULL here (one callback for every data type). When
// every slot is relinquished the door falls back to Relinquish_Default = lock.
bool SetPropertyNull(const uint32_t deviceInstance, const uint16_t objectType,
                     const uint32_t objectInstance, const uint32_t propertyIdentifier,
                     const bool useArrayIndex, const uint32_t propertyArrayIndex,
                     const uint8_t priority, uint32_t* errorCode) {
    (void)useArrayIndex;
    (void)propertyArrayIndex;
    (void)errorCode;
    if (deviceInstance != g_deviceInstance) {
        return false;
    }
    Commandable* c = GetCommandable(objectType, objectInstance);
    if (c != NULL && propertyIdentifier == PROPERTY_IDENTIFIER_PRESENT_VALUE) {
        CommandRelinquish(c, priority);
        printf("WriteProperty: relinquished Access Door %u @ priority %u  (door is now %s)\n",
               objectInstance, EffectivePriority(priority), DoorValueName(ResolveDoorValue(c)));
        return true;
    }
    return false;
}

// -----------------------------------------------------------------------------
// 3. main()
// -----------------------------------------------------------------------------
int main(int argc, char** argv) {
    // Show printf output immediately, even when stdout is piped to a file.
    setvbuf(stdout, NULL, _IONBF, 0);

    // --- Command line + version --------------------------------------------
    // --help / --version print and exit, so handle them before we bind a socket
    // or touch the stack.
    if (CASExampleHelper::HandleHelpAndVersionArgs(argc, argv, APP_NAME, APP_VERSION)) {
        return 0;
    }
    const uint16_t port = CASExampleHelper::ParsePortArg(argc, argv, 47808);
    g_deviceInstance = CASExampleHelper::ParseDeviceIdArg(argc, argv, g_deviceInstance);
    CASExampleHelper::PrintVersion(APP_NAME, APP_VERSION);

    // --- Bind the BACnet/IP socket -----------------------------------------
    if (!CASExampleHelper::SetupUDP(port)) {
        return 1;
    }

    // Capture the BACnet/IP addressing the Network Port object will report.
    g_bacnetIpUdpPort = port;
    if (!CASExampleHelper::GetLocalIPv4(g_ipAddress, g_ipSubnetMask)) {
        printf("FYI: could not read a local IPv4 address; Network Port IP_Address "
               "will report 0.0.0.0.\n");
    }

    // --- Register callbacks -------------------------------------------------
    // The transport + time callbacks are shared boilerplate.
    CASExampleHelper::RegisterCommonCallbacks();
    // The property callbacks are specific to this example.
    BACnetStack_RegisterCallbackGetPropertyReal(GetPropertyReal);
    BACnetStack_RegisterCallbackGetPropertyEnumerated(GetPropertyEnumerated);
    BACnetStack_RegisterCallbackGetPropertyUnsignedInteger(GetPropertyUnsignedInteger);
    BACnetStack_RegisterCallbackGetPropertyCharacterString(GetPropertyCharString);
    BACnetStack_RegisterCallbackGetPropertyBool(GetPropertyBool);
    BACnetStack_RegisterCallbackGetPropertyOctetString(GetPropertyOctetString);
    // The "set" callbacks make this a B-ACDC: they accept WriteProperty (DS-WP-B)
    // to the commandable Access Door (DS-ACAD-B). The door's Present_Value is an
    // Enumerated, so those are the only two setters this profile needs - plus the
    // NULL callback that relinquishes a priority slot.
    BACnetStack_RegisterCallbackSetPropertyEnumerated(SetPropertyEnumerated);
    BACnetStack_RegisterCallbackSetPropertyNull(SetPropertyNull);

    // --- Create the device --------------------------------------------------
    if (!BACnetStack_AddDevice(g_deviceInstance)) {
        printf("Error: Failed to add the Device %u.\n", g_deviceInstance);
        return 1;
    }

    // Enable the two services a B-ACDC must execute: ReadProperty (DS-RP-B) and
    // WriteProperty (DS-WP-B). We set them explicitly to make the profile
    // requirements obvious. Who-Is/I-Am (DM-DDB-B) and Who-Has/I-Have (DM-DOB-B)
    // are answered by the stack automatically and need no service flag.
    //
    // We deliberately do NOT enable ReadPropertyMultiple, SubscribeCOV,
    // DeviceCommunicationControl, or any alarm/event service: a door controller
    // does not require them, so a faithful B-ACDC example leaves them off. (A
    // door controller that reports access EVENTS is a B-ACC/B-AACC instead.)
    if (!BACnetStack_SetServiceEnabled(g_deviceInstance, SERVICE_READ_PROPERTY, true)) {
        printf("Error: Failed to enable the ReadProperty service.\n");
        return 1;
    }
    if (!BACnetStack_SetServiceEnabled(g_deviceInstance, SERVICE_WRITE_PROPERTY, true)) {
        printf("Error: Failed to enable the WriteProperty service.\n");
        return 1;
    }

    // Discovery: Who-Is/I-Am (DM-DDB-B) and Who-Has/I-Have (DM-DOB-B).
    //
    // These need enabling even though the device already ANSWERS them. The
    // stack's service defaults are whoIs + whoHas + readProperty only
    // (BACnetDBDevice.cpp) - iAm and iHave are left FALSE. Who-Is is answered and
    // the start-up I-Am is sent regardless, because neither is gated on the bit;
    // but Protocol_Services_Supported is emitted verbatim from that bitstring, so
    // without these calls the device DOES I-Am and I-Have while telling every
    // client it supports neither. The README claims DM-DDB-B and DM-DOB-B; this
    // is what makes the claim true on the wire.
    if (!BACnetStack_SetServiceEnabled(g_deviceInstance, SERVICE_WHO_IS, true) ||
        !BACnetStack_SetServiceEnabled(g_deviceInstance, SERVICE_I_AM, true) ||
        !BACnetStack_SetServiceEnabled(g_deviceInstance, SERVICE_WHO_HAS, true) ||
        !BACnetStack_SetServiceEnabled(g_deviceInstance, SERVICE_I_HAVE, true)) {
        printf("Error: Failed to enable the discovery services (Who-Is/I-Am, Who-Has/I-Have).\n");
        return 1;
    }
    // --- Add the read-only sensor objects -----------------------------------
    // Every stack setup call returns a bool; a real device should always check
    // it, so this example does too.
    if (!BACnetStack_AddObject(g_deviceInstance, OBJECT_TYPE_ANALOG_INPUT, ANALOG_INPUT_INSTANCE)) {
        printf("Error: Failed to add Analog Input %u (Bronze).\n", ANALOG_INPUT_INSTANCE);
        return 1;
    }
    if (!BACnetStack_AddObject(g_deviceInstance, OBJECT_TYPE_BINARY_INPUT, BINARY_INPUT_INSTANCE)) {
        printf("Error: Failed to add Binary Input %u (Emerald).\n", BINARY_INPUT_INSTANCE);
        return 1;
    }
    if (!BACnetStack_AddObject(g_deviceInstance, OBJECT_TYPE_MULTI_STATE_INPUT, MULTI_STATE_INPUT_INSTANCE)) {
        printf("Error: Failed to add Multi-State Input %u (Hot Pink).\n", MULTI_STATE_INPUT_INSTANCE);
        return 1;
    }

    // --- Add the Access Door (the B-ACDC addition) --------------------------
    // This one object is why the profile exists. It is added with the plain
    // AddObject - the stack has no special Add*Object helper for it.
    if (!BACnetStack_AddObject(g_deviceInstance, OBJECT_TYPE_ACCESS_DOOR, ACCESS_DOOR_INSTANCE)) {
        printf("Error: Failed to add Access Door %u (Cobalt).\n", ACCESS_DOOR_INSTANCE);
        return 1;
    }

    // --- Add the Network Port object ----------------------------------------
    // Every BACnet device (Protocol_Revision 17+) must have at least one Network
    // Port object describing the port it talks on. This one is the BACnet/IP
    // application port; it is the lowest layer, so its reference port is "none".
    if (!BACnetStack_AddNetworkPortObject(
            g_deviceInstance, NETWORK_PORT_INSTANCE,
            NETWORK_PORT_NETWORK_TYPE_IPV4,
            NETWORK_PORT_PROTOCOL_LEVEL_BACNET_APPLICATION,
            NETWORK_PORT_REFERENCE_PORT_NONE)) {
        printf("Error: Failed to add Network Port 1 (Vermilion).\n");
        return 1;
    }

    // --- Enable the OPTIONAL properties we choose to expose ------------------
    // The stack automatically enables an object's REQUIRED properties when the
    // object is added - so Units, Polarity, Number_Of_States, Out_Of_Service, the
    // door's Priority_Array / Relinquish_Default / timing properties, and the
    // Network Port's BACnet/IP addressing are already enabled; our Get* callbacks
    // just supply their values. Only OPTIONAL properties need SetPropertyEnabled.
    //
    // State_Text is optional on a Multi-State Input.
    if (!BACnetStack_SetPropertyEnabled(g_deviceInstance, OBJECT_TYPE_DEVICE,
                                        g_deviceInstance, PROPERTY_IDENTIFIER_DESCRIPTION, true)) {
        printf("Error: Failed to enable Description on the Device object.\n");
        return 1;
    }

    if (!BACnetStack_SetPropertyEnabled(g_deviceInstance, OBJECT_TYPE_MULTI_STATE_INPUT,
                                        MULTI_STATE_INPUT_INSTANCE, PROPERTY_IDENTIFIER_STATE_TEXT, true)) {
        printf("Error: Failed to enable State_Text on Multi-State Input 1 (Hot Pink).\n");
        return 1;
    }

    // Door_Status / Lock_Status / Secured_Status are optional on an Access Door
    // (clause 12.3). We expose them because they are what makes this example
    // legible: they report what the door IS, next to what it was COMMANDED to be.
    if (!BACnetStack_SetPropertyEnabled(g_deviceInstance, OBJECT_TYPE_ACCESS_DOOR,
                                        ACCESS_DOOR_INSTANCE, PROPERTY_IDENTIFIER_DOOR_STATUS, true) ||
        !BACnetStack_SetPropertyEnabled(g_deviceInstance, OBJECT_TYPE_ACCESS_DOOR,
                                        ACCESS_DOOR_INSTANCE, PROPERTY_IDENTIFIER_LOCK_STATUS, true) ||
        !BACnetStack_SetPropertyEnabled(g_deviceInstance, OBJECT_TYPE_ACCESS_DOOR,
                                        ACCESS_DOOR_INSTANCE, PROPERTY_IDENTIFIER_SECURED_STATUS, true)) {
        printf("Error: Failed to enable the Access Door 1 (Cobalt) status properties.\n");
        return 1;
    }

    // --- Make the Access Door commandable -----------------------------------
    // A commandable object's Present_Value is resolved from a 16-slot
    // Priority_Array plus a Relinquish_Default. For the stack to treat the object
    // that way - and to accept WriteProperty into it - Present_Value must be
    // marked WRITABLE. (Present_Value, Priority_Array, and Relinquish_Default are
    // all required properties of an Access Door, so the stack already *enabled*
    // them on AddObject; marking Present_Value writable is what flips the object
    // into commandable mode. We enable the other two explicitly anyway, for
    // clarity - this is the same three-call pattern the B-SA example uses.)
    if (!BACnetStack_SetPropertyEnabled(g_deviceInstance, OBJECT_TYPE_ACCESS_DOOR,
                                        ACCESS_DOOR_INSTANCE, PROPERTY_IDENTIFIER_PRIORITY_ARRAY, true) ||
        !BACnetStack_SetPropertyEnabled(g_deviceInstance, OBJECT_TYPE_ACCESS_DOOR,
                                        ACCESS_DOOR_INSTANCE, PROPERTY_IDENTIFIER_RELINQUISH_DEFAULT, true) ||
        !BACnetStack_SetPropertyWritable(g_deviceInstance, OBJECT_TYPE_ACCESS_DOOR,
                                         ACCESS_DOOR_INSTANCE, PROPERTY_IDENTIFIER_PRESENT_VALUE, true)) {
        printf("Error: Failed to make Access Door 1 (Cobalt) commandable.\n");
        return 1;
    }

    // Who-Is is answered automatically. The spec also requires a device to
    // announce itself on start-up, so broadcast an unsolicited I-Am now (to the
    // local subnet broadcast - the Network Port's own network).
    CASExampleHelper::SendIAm(g_deviceInstance);

    printf("FYI: Device %u (\"%s\") ready. Vendor ID %u. Press 'h' for help.\n",
           g_deviceInstance, DEVICE_NAME, VENDOR_IDENTIFIER);
    printf("FYI: Access Door 1 (Cobalt) starts %s. WriteProperty its Present_Value "
           "(0=lock, 1=unlock) to command it.\n", DoorValueName(ResolveDoorValue(&g_accessDoor)));

    // --- Run the stack ------------------------------------------------------
    // BACnetStack_Tick() processes incoming messages and timers. Call it
    // continuously, and poll the keyboard for interactive commands.
    bool running = true;
    while (running) {
        BACnetStack_Tick();

        switch (CASExampleHelper::PollKey()) {
            case CASExampleHelper::KeyCommand::Help:
                CASExampleHelper::PrintHelp(APP_NAME, APP_VERSION);
                break;
            case CASExampleHelper::KeyCommand::Quit:
                running = false;
                break;
            case CASExampleHelper::KeyCommand::ArrowUp:
                g_analogInput1Value += 1.1f;
                printf("Analog Input 1 (Bronze) = %.1f C\n", g_analogInput1Value);
                break;
            case CASExampleHelper::KeyCommand::ArrowDown:
                g_analogInput1Value -= 1.1f;
                printf("Analog Input 1 (Bronze) = %.1f C\n", g_analogInput1Value);
                break;
            case CASExampleHelper::KeyCommand::None:
            default:
                break;
        }

#if defined(_WIN32)
        Sleep(1); // 1 ms - be a good citizen, don't spin the CPU
#else
        usleep(1000);
#endif
    }

    CASExampleHelper::RestoreInput();
    CASExampleHelper::ShutdownUDP();
    return 0;
}
